# fly.toml app configuration file generated for yasdb on 2026-07-31T09:57:15+12:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'yasdb'
primary_region = 'syd'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '4437'
  YASDB_DATA = '/data/yasdb'
  YASDB_DURABILITY = 'notifier'
  YASDB_FLUSH = '2ms'

[[mounts]]
  source = 'yasdb_data'
  destination = '/data'

[http_service]
  internal_port = 4437
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '10s'
    method = 'GET'
    path = '/__health'

  [http_service.concurrency]
    type = "requests"
    soft_limit = 2000
    hard_limit = 2500

[[vm]]
  cpu_kind = "performance"
  memory = '4gb'
  cpus = 2
  memory_mb = 4096
